### ISSUE TITLE
Неопределена информационная база

### ISSUE THREAD

**Issue by best-tech** [BlackDrak0n/oscript-AutoUpdateIB#3]
Что с этим делать? как найти?

**Comment by 1Cmobile** [comment]
Для серверных баз не хватает кавычек
		СтрокаСоединения = "/IBConnectionString""Srvr = """"&ИмяСервера1СПредприятия""""; Ref = """"&ИмяИнформационнойБазыНаСервере1СПредприятия""""""";

**Comment by 1Cmobile** [comment]
для УправлениеКонфигуратором.УстановитьКлючРазрешенияЗапуска("ПакетноеОбновлениеКонфигурацииИБ");
так не же ошибка в командной строке, не хватает кавычек

**Comment by 1Cmobile** [comment]
а еще не обновляется потому потому что остается зависшее ком соединение.. ну что за жесть то))

**Comment by Tur8008** [comment]
Ага:) Жесть еще та...

**Comment by 1Cmobile** [comment]
сом соединение не закрывается при обновлении конфигурации бд и поэтому появляется ошибка.
Но после ошибки соединение отключается от базы сразу.
Может быть ошибка в движке?
добавил везде 			
ОсвободитьОбъект(Соединение);
всеравно не помогает(

**Comment by 1Cmobile** [comment]
Если везде поставить 
`	ОсвободитьОбъект(Соединение);
	ВыполнитьСборкуМусора();
	Соединение = Неопределено;`
То вроде работает корректно

**Comment by BlackDrak0n** [comment]
Спасибо за ошибку. Замечания учел.

**Comment by Kyrales** [comment]
Где ты учел замечания?

**Comment by Kyrales** [comment]
Косяки как были так и остаются.
